<a href="https://colab.research.google.com/github/smwhite24/deep-learning-challenge/blob/main/deep_learning_module21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df = application_df.drop(columns=['EIN', 'NAME'])

In [ ]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()
print(unique_values)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
# Look at APPLICATION_TYPE value counts
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

# Replace application types with "Other" if they occur fewer than 10 times
application_types_to_replace = application_type_counts[application_type_counts < 10].index
application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(application_types_to_replace, 'Other')

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

# Choose a cutoff value
cutoff_value = 10

application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

# Choose a cutoff value
cutoff_value = 10

# Create a list of classifications to be replaced
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace classifications with "Other"
application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(classifications_to_replace, 'Other')

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_above_one = application_df['CLASSIFICATION'].value_counts()
classification_counts_above_one = classification_counts_above_one[classification_counts_above_one > 1]
print(classification_counts_above_one)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Other       98
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# Choose a cutoff value
cutoff_value = 10

# Create a list of classifications to be replaced
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Other       98
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_converted = pd.get_dummies(application_df,
                                         columns=['AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS', 'APPLICATION_TYPE'])

In [ ]:
application_df_converted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 72 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   STATUS                        34299 non-null  int64
 1   ASK_AMT                       34299 non-null  int64
 2   IS_SUCCESSFUL                 34299 non-null  int64
 3   AFFILIATION_CompanySponsored  34299 non-null  bool
 4   AFFILIATION_Family/Parent     34299 non-null  bool
 5   AFFILIATION_Independent       34299 non-null  bool
 6   AFFILIATION_National          34299 non-null  bool
 7   AFFILIATION_Other             34299 non-null  bool
 8   AFFILIATION_Regional          34299 non-null  bool
 9   CLASSIFICATION_C1000          34299 non-null  bool
 10  CLASSIFICATION_C1200          34299 non-null  bool
 11  CLASSIFICATION_C1230          34299 non-null  bool
 12  CLASSIFICATION_C1238          34299 non-null  bool
 13  CLASSIFICATION_C1240          34299 non-null  bool
 14  CLASSIFICATION_C1250          34299 non-null  bool
 15  CLASSIFICATION_C1270          34299 non-null  bool
 16  CLASSIFICATION_C1278          34299 non-null  bool
 17  CLASSIFICATION_C1280          34299 non-null  bool
 18  CLASSIFICATION_C1300          34299 non-null  bool
 19  CLASSIFICATION_C1400          34299 non-null  bool
 20  CLASSIFICATION_C1500          34299 non-null  bool
 21  CLASSIFICATION_C1700          34299 non-null  bool
 22  CLASSIFICATION_C1800          34299 non-null  bool
 23  CLASSIFICATION_C2000          34299 non-null  bool
 24  CLASSIFICATION_C2100          34299 non-null  bool
 25  CLASSIFICATION_C2300          34299 non-null  bool
 26  CLASSIFICATION_C2700          34299 non-null  bool
 27  CLASSIFICATION_C2800          34299 non-null  bool
 28  CLASSIFICATION_C3000          34299 non-null  bool
 29  CLASSIFICATION_C4000          34299 non-null  bool
 30  CLASSIFICATION_C5000          34299 non-null  bool
 31  CLASSIFICATION_C6000          34299 non-null  bool
 32  CLASSIFICATION_C7000          34299 non-null  bool
 33  CLASSIFICATION_C7100          34299 non-null  bool
 34  CLASSIFICATION_C7120          34299 non-null  bool
 35  CLASSIFICATION_C7200          34299 non-null  bool
 36  CLASSIFICATION_C8000          34299 non-null  bool
 37  CLASSIFICATION_C8200          34299 non-null  bool
 38  CLASSIFICATION_Other          34299 non-null  bool
 39  USE_CASE_CommunityServ        34299 non-null  bool
 40  USE_CASE_Heathcare            34299 non-null  bool
 41  USE_CASE_Other                34299 non-null  bool
 42  USE_CASE_Preservation         34299 non-null  bool
 43  USE_CASE_ProductDev           34299 non-null  bool
 44  ORGANIZATION_Association      34299 non-null  bool
 45  ORGANIZATION_Co-operative     34299 non-null  bool
 46  ORGANIZATION_Corporation      34299 non-null  bool
 47  ORGANIZATION_Trust            34299 non-null  bool
 48  INCOME_AMT_0                  34299 non-null  bool
 49  INCOME_AMT_1-9999             34299 non-null  bool
 50  INCOME_AMT_10000-24999        34299 non-null  bool
 51  INCOME_AMT_100000-499999      34299 non-null  bool
 52  INCOME_AMT_10M-50M            34299 non-null  bool
 53  INCOME_AMT_1M-5M              34299 non-null  bool
 54  INCOME_AMT_25000-99999        34299 non-null  bool
 55  INCOME_AMT_50M+               34299 non-null  bool
 56  INCOME_AMT_5M-10M             34299 non-null  bool
 57  SPECIAL_CONSIDERATIONS_N      34299 non-null  bool
 58  SPECIAL_CONSIDERATIONS_Y      34299 non-null  bool
 59  APPLICATION_TYPE_Other        34299 non-null  bool
 60  APPLICATION_TYPE_T10          34299 non-null  bool
 61  APPLICATION_TYPE_T12          34299 non-null  bool
 62  APPLICATION_TYPE_T13          34299 non-null  bool
 63  APPLICATION_TYPE_T19          34299 non-null  bool
 64  APPLICATION_TYPE_T2           34299 non-null  bool
 65  APPLICATION_TYPE_T3           34299 non-null  bool
 66  APPLICATION_TYPE_T4           34299 non-null  bool
 67  APPLICATION_TYPE_T5           34299 non-null  bool
 68  APPLICATION_TYPE_T6           34299 non-null  bool
 69  APPLICATION_TYPE_T7           34299 non-null  bool
 70  APPLICATION_TYPE_T8           34299 non-null  bool
 71  APPLICATION_TYPE_T9           34299 non-null  bool
dtypes: bool(69), int64(3)
memory usage: 3.0 MB

In [ ]:
# Split our preprocessed data into our features and target arrays
# Define the target variable
y = application_df_converted['IS_SUCCESSFUL']
X = application_df_converted.drop(columns=['IS_SUCCESSFUL'])

# Split the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [ ]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training data
X_train_scaled = scaler.transform(X_train)

# Scale the test data
X_test_scaled = scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the number of input features
input_features = X_train_scaled.shape[1]

# Create the Sequential model
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=10, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=10, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │             720 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 841 (3.29 KB)

 Trainable params: 841 (3.29 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.6369 - loss: 0.6459 - val_accuracy: 0.7195 - val_loss: 0.5737
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7380 - loss: 0.5537 - val_accuracy: 0.7217 - val_loss: 0.5662
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7342 - loss: 0.5492 - val_accuracy: 0.7228 - val_loss: 0.5651
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7337 - loss: 0.5473 - val_accuracy: 0.7254 - val_loss: 0.5654
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7372 - loss: 0.5423 - val_accuracy: 0.7265 - val_loss: 0.5653
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7378 - loss: 0.5428 - val_accuracy: 0.7263 - val_loss: 0.5619
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7396 - loss: 0.5410 - val_accuracy: 0.7254 - val_loss: 0.5617
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7346 - loss: 0.5462 - val_accuracy: 0.7269 - val_loss: 0.5607
Epoch 9/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7399 - loss: 0.5400 - val_accuracy: 0.7277 - val_loss: 0.5606
Epoch 10/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7373 - loss: 0.5425 - val_accuracy: 0.7250 - val_loss: 0.5611
Epoch 11/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7378 - loss: 0.5414 - val_accuracy: 0.7269 - val_loss: 0.5594
Epoch 12/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7438 - loss: 0.5340 - val_accuracy: 0.7261 - val_loss: 0.5600
Epoch 13/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7396 - loss: 0.5364 - val_accuracy: 0.7261 - val_loss: 0.5610
Epoch 14/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7326 - loss: 0.5437 - val_accuracy: 0.7275 - val_loss: 0.5606
Epoch 15/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7397 - loss: 0.5338 - val_accuracy: 0.7248 - val_loss: 0.5597
Epoch 16/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7390 - loss: 0.5341 - val_accuracy: 0.7259 - val_loss: 0.5596
Epoch 17/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7397 - loss: 0.5368 - val_accuracy: 0.7269 - val_loss: 0.5590
Epoch 18/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7400 - loss: 0.5363 - val_accuracy: 0.7261 - val_loss: 0.5607
Epoch 19/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7388 - loss: 0.5338 - val_accuracy: 0.7244 - val_loss: 0.5602
Epoch 20/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7418 - loss: 0.5373 - val_accuracy: 0.7263 - val_loss: 0.5597
Epoch 21/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7323 - loss: 0.5419 - val_accuracy: 0.7244 - val_loss: 0.5596
Epoch 22/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7380 - loss: 0.5349 - val_accuracy: 0.7242 - val_loss: 0.5593
Epoch 23/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7379 - loss: 0.5371 - val_accuracy: 0.7236 - val_loss: 0.5621
Epoch 24/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7303 - loss: 0.5431 - val_accuracy: 0.7254 - val_loss: 0.5608
Epoch 25/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7464 - loss: 0.5280 - val_accuracy: 0.7246 - val_loss: 0.5602
Epoch 26/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7332 - loss: 0.5417 - val_accuracy: 0.7273 - val_loss: 0.5612
Epoch 27/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7341 - loss: 0.5424 - val_accuracy: 0.7256 - val_loss: 0.5613
Epoch 28/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7359 - loss: 0.5412 - val_accuracy: 0.7265 - val_loss: 0.5609
Epoch 29/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7423 - loss: 0.5351 - val_accuracy: 0.7252 - val_loss: 0.5599
Epoch 30/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7406 - loss: 0.5370 - val_accuracy: 0.7250 - val_loss: 0.5623
Epoch 31/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7437 - loss: 0.5290 - val_accuracy: 0.7263 - val_loss: 0.5587
Epoch 32/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7417 - loss: 0.5346 - val_accuracy: 0.7252 - val_loss: 0.5623
Epoch 33/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7352 - loss: 0.5388 - val_accuracy: 0.7261 - val_loss: 0.5611
Epoch 34/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7386 - loss: 0.5402 - val_accuracy: 0.7263 - val_loss: 0.5623
Epoch 35/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7377 - loss: 0.5354 - val_accuracy: 0.7250 - val_loss: 0.5604
Epoch 36/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7380 - loss: 0.5337 - val_accuracy: 0.7248 - val_loss: 0.5600
Epoch 37/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7403 - loss: 0.5373 - val_accuracy: 0.7256 - val_loss: 0.5619
Epoch 38/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7433 - loss: 0.5319 - val_accuracy: 0.7265 - val_loss: 0.5615
Epoch 39/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7346 - loss: 0.5390 - val_accuracy: 0.7252 - val_loss: 0.5629
Epoch 40/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7372 - loss: 0.5379 - val_accuracy: 0.7279 - val_loss: 0.5617
Epoch 41/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7362 - loss: 0.5400 - val_accuracy: 0.7250 - val_loss: 0.5646
Epoch 42/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7409 - loss: 0.5345 - val_accuracy: 0.7244 - val_loss: 0.5604
Epoch 43/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7410 - loss: 0.5351 - val_accuracy: 0.7244 - val_loss: 0.5633
Epoch 44/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7342 - loss: 0.5407 - val_accuracy: 0.7258 - val_loss: 0.5635
Epoch 45/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7437 - loss: 0.5314 - val_accuracy: 0.7275 - val_loss: 0.5614
Epoch 46/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7443 - loss: 0.5332 - val_accuracy: 0.7269 - val_loss: 0.5609
Epoch 47/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7372 - loss: 0.5390 - val_accuracy: 0.7236 - val_loss: 0.5622
Epoch 48/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7323 - loss: 0.5445 - val_accuracy: 0.7258 - val_loss: 0.5632
Epoch 49/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7392 - loss: 0.5364 - val_accuracy: 0.7254 - val_loss: 0.5615
Epoch 50/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7385 - loss: 0.5363 - val_accuracy: 0.7259 - val_loss: 0.5610
Epoch 51/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7407 - loss: 0.5377 - val_accuracy: 0.7242 - val_loss: 0.5626
Epoch 52/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7386 - loss: 0.5346 - val_accuracy: 0.7267 - val_loss: 0.5638
Epoch 53/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7368 - loss: 0.5401 - val_accuracy: 0.7244 - val_loss: 0.5612
Epoch 54/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7371 - loss: 0.5382 - val_accuracy: 0.7261 - val_loss: 0.5607
Epoch 55/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7461 - loss: 0.5297 - val_accuracy: 0.7256 - val_loss: 0.5604
Epoch 56/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7443 - loss: 0.5333 - val_accuracy: 0.7250 - val_loss: 0.5609
Epoch 57/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7383 - loss: 0.5365 - val_accuracy: 0.7242 - val_loss: 0.5623
Epoch 58/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7447 - loss: 0.5309 - val_accuracy: 0.7265 - val_loss: 0.5624
Epoch 59/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7421 - loss: 0.5359 - val_accuracy: 0.7230 - val_loss: 0.5612
Epoch 60/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7429 - loss: 0.5340 - val_accuracy: 0.7254 - val_loss: 0.5606
Epoch 61/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7384 - loss: 0.5377 - val_accuracy: 0.7273 - val_loss: 0.5606
Epoch 62/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7350 - loss: 0.5407 - val_accuracy: 0.7248 - val_loss: 0.5612
Epoch 63/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7396 - loss: 0.5388 - val_accuracy: 0.7267 - val_loss: 0.5612
Epoch 64/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7438 - loss: 0.5319 - val_accuracy: 0.7250 - val_loss: 0.5603
Epoch 65/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7424 - loss: 0.5335 - val_accuracy: 0.7273 - val_loss: 0.5607
Epoch 66/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7443 - loss: 0.5277 - val_accuracy: 0.7269 - val_loss: 0.5607
Epoch 67/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7473 - loss: 0.5284 - val_accuracy: 0.7275 - val_loss: 0.5600
Epoch 68/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7379 - loss: 0.5367 - val_accuracy: 0.7242 - val_loss: 0.5615
Epoch 69/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7410 - loss: 0.5383 - val_accuracy: 0.7258 - val_loss: 0.5620
Epoch 70/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7383 - loss: 0.5361 - val_accuracy: 0.7256 - val_loss: 0.5630
Epoch 71/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7481 - loss: 0.5272 - val_accuracy: 0.7261 - val_loss: 0.5610
Epoch 72/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7428 - loss: 0.5333 - val_accuracy: 0.7244 - val_loss: 0.5615
Epoch 73/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7442 - loss: 0.5311 - val_accuracy: 0.7265 - val_loss: 0.5597
Epoch 74/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7405 - loss: 0.5371 - val_accuracy: 0.7258 - val_loss: 0.5609
Epoch 75/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7393 - loss: 0.5349 - val_accuracy: 0.7267 - val_loss: 0.5615
Epoch 76/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7444 - loss: 0.5299 - val_accuracy: 0.7256 - val_loss: 0.5619
Epoch 77/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7398 - loss: 0.5358 - val_accuracy: 0.7252 - val_loss: 0.5631
Epoch 78/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7399 - loss: 0.5325 - val_accuracy: 0.7261 - val_loss: 0.5613
Epoch 79/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7404 - loss: 0.5351 - val_accuracy: 0.7248 - val_loss: 0.5611
Epoch 80/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7452 - loss: 0.5300 - val_accuracy: 0.7259 - val_loss: 0.5629
Epoch 81/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7443 - loss: 0.5272 - val_accuracy: 0.7246 - val_loss: 0.5602
Epoch 82/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7420 - loss: 0.5298 - val_accuracy: 0.7252 - val_loss: 0.5631
Epoch 83/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7450 - loss: 0.5301 - val_accuracy: 0.7258 - val_loss: 0.5628
Epoch 84/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7419 - loss: 0.5318 - val_accuracy: 0.7267 - val_loss: 0.5612
Epoch 85/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7406 - loss: 0.5392 - val_accuracy: 0.7261 - val_loss: 0.5626
Epoch 86/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7412 - loss: 0.5343 - val_accuracy: 0.7248 - val_loss: 0.5613
Epoch 87/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7457 - loss: 0.5329 - val_accuracy: 0.7240 - val_loss: 0.5609
Epoch 88/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7418 - loss: 0.5356 - val_accuracy: 0.7250 - val_loss: 0.5612
Epoch 89/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7451 - loss: 0.5329 - val_accuracy: 0.7263 - val_loss: 0.5607
Epoch 90/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7402 - loss: 0.5312 - val_accuracy: 0.7254 - val_loss: 0.5608
Epoch 91/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7415 - loss: 0.5287 - val_accuracy: 0.7242 - val_loss: 0.5615
Epoch 92/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7411 - loss: 0.5324 - val_accuracy: 0.7246 - val_loss: 0.5609
Epoch 93/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7451 - loss: 0.5316 - val_accuracy: 0.7246 - val_loss: 0.5613
Epoch 94/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7446 - loss: 0.5304 - val_accuracy: 0.7246 - val_loss: 0.5618
Epoch 95/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7448 - loss: 0.5327 - val_accuracy: 0.7248 - val_loss: 0.5623
Epoch 96/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7419 - loss: 0.5320 - val_accuracy: 0.7246 - val_loss: 0.5619
Epoch 97/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7398 - loss: 0.5352 - val_accuracy: 0.7256 - val_loss: 0.5626
Epoch 98/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7404 - loss: 0.5306 - val_accuracy: 0.7240 - val_loss: 0.5620
Epoch 99/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7463 - loss: 0.5262 - val_accuracy: 0.7250 - val_loss: 0.5613
Epoch 100/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7474 - loss: 0.5285 - val_accuracy: 0.7244 - val_loss: 0.5625

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 1ms/step - accuracy: 0.7261 - loss: 0.5543
Loss: 0.5542532801628113, Accuracy: 0.726064145565033

In [ ]:
# Export our model to HDF5 file
nn.save("my_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
nn.save('my_model.keras')